[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$M0aoNWas1frfe29NiRECwA$2bS9efXSR2mZfiV2nGdNrB4VROSA09KbldLJYvybwXeKXOzBTt9iSSFVo7m2iCc3.OWT7SSYYb2WGDwdZcBfpg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

